config/routes.rb
Rails.application.routes.draw do

  root 'movies#home'

  resources :session, only: [:new, :create]
  get '/logout' => 'session#logout'

  get '/movies/:movie_id/showtimes/:showtime_id/receipts', to: 'receipts#movie_index', as: 'receipt_by_movie'

  resources :auditoriums do
    resources :showtimes, only: [:create, :new]
  end
  resources :receipts, only: [:index]

  resources :movies do
    resources :showtimes, except: [:create, :new] do
      resources :receipts, only: [:create, :new]
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authorize, except: [:home, :show]

  def home
    @movies = Movie.all

    render :home
  end

  def index
    @movies = Movie.all

    render :index
  end

  def create
    @movie = Movie.new(name: params[:movie][:name], pic_url: params[:movie][:pic_url], hours: params[:movie][:hours], minutes: params[:movie][:minutes], starring: params[:movie][:starring], tagline: params[:movie][:tagline], plot: params[:movie][:plot])

    if @movie.save
      redirect_to movies_path
    else
      @errors = @errors.full_messages
      render :new
    end
  end

  def new
    @movie = Movie.new

    render :new
  end

  def show
    @movie = Movie.find(params[:id])

    @showtimes = @movie.showtimes.all

    render :show
  end

  def edit
    @movie = Movie.find(params[:id])

    render :edit
  end

  def update


    @movie = Movie.find(params[:id])

    if @movie.update_attributes!(name: params[:movie][:name], pic_url: params[:movie][:pic_url], hours: params[:movie][:hours], minutes: params[:movie][:minutes], starring: params[:movie][:starring], tagline: params[:movie][:tagline], plot: params[:movie][:plot])

      redirect_to movie_path(@movie)
    else
      @errors = @movie.errors.full_messages
      render :edit
    end

  end

  def destroy


    @movie = Movie.find(params[:id])

    @movie.destroy

    redirect_to (:root)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/edit.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <%= form_for @movie, method: :put do |m| %>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Name:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :name %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Picture URL:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :pic_url %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Hours Long:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :hours %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Minutes Long:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :minutes %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Plot" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_area :plot%>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Tag Line" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_area :tagline %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Starring:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :starring%>
        </div>
      </div>
      <div class = "row center-row">
        <%= m.submit "Edit Movie", class: 'submit-button' %>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h3 class="errors-header">ERRORS:</h3>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/home.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
    <h1 class = "header">Welcome To Movies on Rails</h1>
    </div>
    <div class = "row center-row not-mobile">
      <div class = "col-md-4">
        <p class>Poster</p>
      </div>
      <div class = "col-md-4">
        <p class>Movie Name</p>
      </div>
      <div class = "col-md-4">
        <p class>Tagline</p>
      </div>
    </div>
    <% @movies.each do |movie| %>
      <% if movie.showtimes.length >= 1 %>
        <div class = "row center-row">
          <div class = "col-md-4">
            <%= link_to image_tag(movie.pic_url), movie_path(movie.id)%>
          </div>
          <div class = "col-md-4">
            <h2><%= movie.name %> </h2>
          </div>
          <div class = "col-md-4">
            <p><%= movie.tagline %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<% if logged_in? %>
  <div class = "container-fluid">
    <div class = "jumbotron">
      <div class = "row center-row">
        <div class = "col-md-4">
          <div class = "row center-row" >
            <p>Total Sales: <%= number_to_currency(Receipt.total_sales) %></p>
          </div>
          <div class = "row center-row">
            <%= link_to "Sales Index", receipts_path %>
          </div>
        </div>
        <div class = "col-md-4">
          <div class = "row center-row">
            <%= link_to "Create New Movie", new_movie_path %>
          </div>
          <div class = "row center-row">
            <%= link_to "Movie Index", movies_path %>
          </div>
        </div>
        <div class = "col-md-4">
          <div class = "row center-row">
          <%= link_to "Construct New Auditorium", new_auditorium_path %>
          </div>
          <div class = "row center-row">
          <%= link_to "Auditorium Index", auditoriums_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/index.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <h1>Movies</h1>
    </div>
    <div class = "row center-row">
      <% @movies.each do |movie| %>
        <div class = "row center-row">
          <div class = "col-md-4">
            <%= link_to image_tag(movie.pic_url), movie_path(movie.id)%>
          </div>
          <div class = "col-md-4">
            <h2><%= movie.name %> </h2>
          </div>
          <div class = "col-md-4">
            <p><%= movie.tagline %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <%= form_for @movie do |m| %>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Name:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :name %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Picture URL:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :pic_url %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Hours Long:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :hours %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Minutes Long:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :minutes %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Plot:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_area :plot%>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Tag Line:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_area :tagline %>
        </div>
      </div>
      <div class = "row center-row">
        <div class = "col-md-6 row-align-right">
          <%= m.label "Starring:" %>
        </div>
        <div class = "col-md-6 row-align-left">
          <%= m.text_field :starring%>
        </div>
      </div>
      <div class = "row center-row">
        <%= m.submit "Create New Movie", class: 'submit-button' %>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h1 class="errors-header">ERRORS:</h1>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <h1><%= @movie.name %></h1>
    </div>

    <div class = "row center-row">
      <%= image_tag("#{@movie.pic_url}") %>
    </div>
    <div class = "row">
      <div class = "col-md-8" >
        <div class = "row">
          <p>Starring: <%= @movie.starring %>
        </div>
        <div class = "row">
          <p>Tagline: </p><%= simple_format(@movie.tagline) %>
        </div>
        <div class = "row">
          <p>Description: </p><%= simple_format(@movie.plot) %>
        </div>
      </div>
      <div class = "col-md-4">
        <div class = "row center-row table-row">
          <p>Showtimes</p>
        </div>
        <% @showtimes.order(start: :asc).each do |showtime| %>
          <div class = "row center-row table-row">
            <% if showtime.tickets_available? || showtime.start < Time.now %>
              <p> <%= showtime.start.strftime("%r") %></p>
            <% else %>
              <p><%= link_to showtime.start.strftime("%r"), movie_showtime_path(@movie, showtime.id) %></p>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if logged_in? %>
  <div class = "container-fluid">
    <div class = "jumbotron">
      <div class = "row center-row">
        <div class = "col-md-4">
          <div class = "row center-row">
            <p><%= @movie.name %>'s Total Sales: <%= number_to_currency(Receipt.total_sales_by_movie(@movie.id)) %></p>
          </div>
        </div>
        <div class = "col-md-4">
          <%= link_to "Edit Movie", edit_movie_path(@movie) %>
        </div>
        <div class = "col-md-4">
          <%= form_for @movie, method: :delete do |m| %>
            <%= m.submit "Delete Movie", class: 'submit-button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>