config/routes.rb
Rails.application.routes.draw do

  root 'movies#home'

  resources :session, only: [:new, :create]
  get '/logout' => 'session#logout'

  get '/movies/:movie_id/showtimes/:showtime_id/receipts', to: 'receipts#movie_index', as: 'receipt_by_movie'

  resources :auditoriums do
    resources :showtimes, only: [:create, :new]
  end
  resources :receipts, only: [:index]

  resources :movies do
    resources :showtimes, except: [:create, :new] do
      resources :receipts, only: [:create, :new]
    end
  end

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base

  has_many :showtimes

end

app/controllers/auditoriums_controller.rb
class AuditoriumsController < ApplicationController

  before_action :authorize

  def index
    @auditoriums = Auditorium.all

    render :index
  end

  def create

    @auditorium = Auditorium.new(capacity: params[:auditorium][:capacity])

    if @auditorium.save
      redirect_to auditoriums_path
    else
      @errors = @auditorium.errors.full_messages
      render :new
    end
  end

  def new

    @auditorium = Auditorium.new

    render :new
  end

  def edit

    @auditorium = Auditorium.find(params[:id])

    render :edit
  end

  def show

    @auditorium = Auditorium.find(params[:id])

    render :show
  end

  def update

    @auditorium = Auditorium.find(params[:id])

    if @auditorium.update_attributes!(capacity: params[:auditorium][:capacity])
      redirect_to auditoriums_path
    else
      @errors = @auditorium.errors.full_messages
      render :edit
    end
  end

  def destroy

    @auditorium = Auditorium.find(params[:id])

    @auditorium.destroy

    redirect_to auditoriums_path
  end

end

app/helpers/auditoriums_helper.rb
module AuditoriumsHelper
end

app/views/auditoriums/edit.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <%= form_for @auditorium, method: :put do |a| %>
      <div class = "row center-row">
        <%= a.label "Capacity:" %>
        <%= a.text_field :capacity %>
      </div>
      <div class = "row center-row">
        <%= a.submit "Edit Auditorium", class: 'submit-button' %>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h3 class="errors-header">ERRORS:</h3>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/auditoriums/index.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <h1>Auditoriums</h1>
    </div>
    <div class = "row center-row not-mobile">
      <div class = "col-md-4">
        <p>Auditorium Number</p>
      </div>
      <div class = "col-md-4">
        <p>Auditorium Capacity</p>
      </div>
      <div class = "col-md-4">
      </div>
    </div>
    <div class = "row center-row">
      <% @auditoriums.each do |auditorium| %>
        <div class = "col-md-4">
          <p><%= auditorium.id %><%= link_to " View / Add Showtime For", auditorium_path(auditorium.id) %></p>
        </div>
        <div class = "col-md-4">
          <p><%= auditorium.capacity %></p>
        </div>
        <div class = "col-md-4">
          <div class = "row center-row">
            <p><%= link_to "Edit Auditorium", edit_auditorium_path(auditorium) %></p>
          </div>
          <div class = "row center-row">
            <%= form_for auditorium, method: :delete do |a| %>
              <%= a.submit "Destroy Auditorium", class: 'submit-button' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/auditoriums/new.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <%= form_for @auditorium, url: url_for(action: 'create', controller: 'auditoriums') do |a| %>
      <div class = "row center-row">
        <%= a.label "Capacity:" %>
        <%= a.text_field :capacity %>
      </div>
      <div class = "row center-row">
        <%= a.submit "Create New Auditorium", class: 'submit-button'%>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h3 class="errors-header">ERRORS:</h3>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/auditoriums/show.html.erb
<div class = "containter-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <h1>Auditorium Number: <%= @auditorium.id %></h1>
    </div>
    <div class = "row center-row">
      <div class = "col-md-4">
        <%= @auditorium.id %>
      </div>
      <div class = "col-md-4">
        <%= @auditorium.capacity %>
      </div>
      <div class = "col-md-4">
        <% @auditorium.showtimes.each do |showtime| %>
          <div class = "row center-row">
            <%= showtime.start.strftime("%r") %>
          </div>
        <% end %>
        <% if logged_in? %>
          <div class = "row center-row">
            <%= link_to "Create New Showtime", new_auditorium_showtime_path(@auditorium) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>