config/routes.rb
Rails.application.routes.draw do

  root 'movies#home'

  resources :session, only: [:new, :create]
  get '/logout' => 'session#logout'

  get '/movies/:movie_id/showtimes/:showtime_id/receipts', to: 'receipts#movie_index', as: 'receipt_by_movie'

  resources :auditoriums do
    resources :showtimes, only: [:create, :new]
  end
  resources :receipts, only: [:index]

  resources :movies do
    resources :showtimes, except: [:create, :new] do
      resources :receipts, only: [:create, :new]
    end
  end

end

app/models/showtime.rb
class Showtime < ActiveRecord::Base
  include ActiveModel::Validations

  belongs_to :movie

  belongs_to :auditorium

  has_many :receipts

  validate do |showtime|
    showtime.auditorium_available?
  end


  def available_seats
    taken_seats = self.receipts.length
    return self.auditorium.capacity - taken_seats
  end

  def tickets_available?
    if self.available_seats <= 0
      errors.add(:auditorium_id, :no_seats_avail, message: "There aren't any more available seats for this showtime.")
    end
  end

  def auditorium_available?
    Showtime.where(auditorium_id: self.auditorium_id).each do |showtime|
      if self.start.between?(showtime.start, showtime.finish) || self.finish.between?(showtime.start, showtime.finish)
        errors.add(:start, :invalid_time, message: "Auditorium currently in use when this showtime would be viewing.")
        return false
      else
        return true
      end
    end
  end

end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController

  before_action :authorize, except: [:show]

  def create
    @auditorium = Auditorium.find(params[:auditorium_id])
    @movie = Movie.find_by(name: params[:showtime][:movie_id])

    @start = DateTime.new(params[:showtime]["start(1i)"].to_i, params[:showtime]["start(2i)"].to_i, params[:showtime]["start(3i)"].to_i, params[:showtime]["start(4i)"].to_i, params[:showtime]["start(5i)"].to_i)

    @finish = @start + @movie.hours.hours + @movie.minutes.minutes

    @showtime = @auditorium.showtimes.new(price: params[:showtime][:price], start: @start, finish: @finish, auditorium: @auditorium, movie: @movie)

    if @showtime.save!(price: params[:showtime][:price], start: @start, finish: @finish, auditorium: @auditorium, movie: @movie)
      redirect_to movie_path(@movie)
    else
      @errors = @showtime.errors.full_messages
      render :new
    end
  end

  def new

    @movies = Movie.all

    @auditorium = Auditorium.find(params[:auditorium_id])

    @showtimes = @auditorium.showtimes.all

    @showtime = @auditorium.showtimes.new

    render :new
  end

  def show
    @movie = Movie.find(params[:movie_id])

    @showtime = @movie.showtimes.find(params[:id])

    @auditorium = @showtime.auditorium

    render :show
  end

  def edit
    @movie = Movie.find(params[:movie_id])

    @movies = Movie.all

    @auditoriums = Auditorium.all

    @showtime = @movie.showtimes.find(params[:id])

    render :edit
  end

  def update
    @movie = Movie.find(params[:movie_id])

    @showtime = @movie.showtimes.find(params[:id])

    @auditorium = @showtime.auditorium

    @start = DateTime.new(params[:showtime]["start(1i)"].to_i, params[:showtime]["start(2i)"].to_i, params[:showtime]["start(3i)"].to_i, params[:showtime]["start(4i)"].to_i, params[:showtime]["start(5i)"].to_i)

    @finish = @start + @movie.hours.hours + @movie.minutes.minutes

    if @showtime.update_attributes!(price: params[:showtime][:price], start: @start, finish: @finish, auditorium: @auditorium, movie: @movie)

      redirect_to movie_path(@movie)
    else
      @erros = @showtime.errors.full_messages
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])

    @showtime = @movie.showtimes.find(params[:id])

    @showtime.destroy

    redirect_to movie_path(@movie)
  end
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper

end

app/views/showtimes/edit.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <p>Edit Showtime</p>
    </div>
    <%= form_for [@movie, @showtime], method: :put do |s| %>
      <div class = "row center-row">
        <div class = "col-md-6">
          <% @movies.each do |movie| %>
            <div class= "row">
            <%= movie.name %>:  <%= s.radio_button(:movie_id, "#{movie.name}") %>
            </div>
          <% end %>
        </div>
        <div class = "col-md-6">
          <div class = "row center-row">
            <%= s.label "Price" %>
          </div>
          <div class = "row center-row">
            <%= s.text_field :price %>
          </div>
          <div class = "row center-row">
            <%= s.label "Start Time"%>
          </div>
          <div class = "row center-row">
            <%= s.datetime_select :start %>
          </div>
        </div>
      </div>
      <div class = "row center-row">
        <%=s.submit "Edit Showtime", class: 'submit-button' %>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h3 class="errors-header">ERRORS:</h3>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/showtimes/new.html.erb
<div class = "container-fluid">
  <div class = "jumbotron">
    <div class = "row center-row">
      <p>Create Showtime For Auditorium <%= @auditorium.id %></p>
    </div>
    <%= form_for [@auditorium, @showtime] do |s| %>
      <div class = "row center-row">
        <div class = "col-md-6">
          <% @movies.each do |movie| %>
            <div class= "row">
            <%= movie.name %>:  <%= s.radio_button(:movie_id, "#{movie.name}") %>
            </div>
          <% end %>
        </div>
        <div class = "col-md-6">
          <div class = "row center-row">
            <%= s.label "Price" %>
          </div>
          <div class = "row center-row">
            <%= s.text_field :price %>
          </div>
          <div class = "row center-row">
            <%= s.label "Start Time"%>
          </div>
          <div class = "row center-row">
            <%= s.datetime_select :start %>
          </div>
        </div>
        <div class = "row center-row">
          <%= s.submit "Create New Showtime", class: 'submit-button' %>
        </div>
      <% end %>
    </div>
    <div class = "row center-row">
      <h1>Current Start Times</h1>
    </div>
    <% @showtimes.order(start: :asc).each do |showtime| %>
      <div class = "row center-row">
        <%= showtime.start.strftime("%r") %>
      </div>
    <% end %>
    <% if @errors %>
      <div class="errors-container">
        <h3 class="errors-header">ERRORS:</h3>
        <ol class="errors-list">
          <% @errors.uniq.each do |error| %>
            <li class="error-list-item"><%= error %></li>
          <% end %>
        </ol>
      </div>
    <% end %>
  </div>
</div>

app/views/showtimes/show.html.erb
<div class = "fluid-container">
  <div class = "jumbotron">
    <div class = "row center-row">
      <h1><%= @movie.name %></h1>
    </div>
    <div class = "row center-row">
      <%= image_tag @movie.pic_url %>
    </div>
    <div class = "row center-row">
      <div class ="col-md-4 table-row">
        <div class = "row">
          <h3 class>Price</h3>
        </div>
        <div class ="row">
          <p><%= number_to_currency(@showtime.price) %></p>
        </div>
      </div>
      <div class ="col-md-4 table-row">
        <div class = "row">
          <h3 class>Start Time</h3>
        </div>
        <div class ="row">
          <p><%= @showtime.start.strftime("%r") %></p>
        </div>
      </div>
      <div class ="col-md-4 table-row">
        <div class = "row">
          <h3 class>Auditorium</h3>
        </div>
        <div class ="row">
          <p><%= @auditorium.id  %></p>
        </div>
      </div>
    </div>
    <div class = "row center-row row-above-margin">
      <div class = "col-md-4">
        <p>Available Seats: <%= @showtime.available_seats%></p>
      </div>
      <div class = "col-md-4">
        <%= link_to "Return to: #{@movie.name}", movie_path(@movie.id) %>
      </div>
      <div class = "col-md-4">
        <%= link_to "Purchase Ticket", new_movie_showtime_receipt_path(@movie.id, @showtime.id) %>
      </div>
    </div>
  </div>
</div>
<% if logged_in? %>
  <div class = "container-fluid">
    <div class = "jumbotron">
      <div class = "row center-row">
        <div class = "col-md-4">
          <%= link_to "Index of Sales For This Movie", receipt_by_movie_path(@movie.id, @showtime.id) %>
        </div>
        <div class = "col-md-4">
          <%= link_to "Edit Showtime", edit_movie_showtime_path(@movie.id, @showtime.id) %>
        </div>
        <div class = "col-md-4">
          <%= form_for [@movie, @showtime], method: :delete do |m| %>
            <%= m.submit "Delete Showtime", class: 'submit-button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>