config/routes.rb
Rails.application.routes.draw do

  root 'movies#home'

  resources :session, only: [:new, :create]
  get '/logout' => 'session#logout'

  get '/movies/:movie_id/showtimes/:showtime_id/receipts', to: 'receipts#movie_index', as: 'receipt_by_movie'

  resources :auditoriums do
    resources :showtimes, only: [:create, :new]
  end
  resources :receipts, only: [:index]

  resources :movies do
    resources :showtimes, except: [:create, :new] do
      resources :receipts, only: [:create, :new]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>MovieOnRails</title>
<head>
  <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <p class="navbar-brand">Movies on Rails</p>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Admin Login", new_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

      <%= yield %>

</body>
</html>